global:
  repoURL: "https://github.com/phuchoang2603/realtime-credit-card-fraud-detection.git"
  targetRevision: "main"
  destinationServer: "https://kubernetes.default.svc"

applications:
  loki:
    enabled: true
    destinationNamespace: monitoring
    # chartURL: "https://github.com/another-org/loki-chart-repo.git"
    # chartTargetRevision: "v1.2.3"
    path: deployments/helm-charts/loki
    # valuesURL: "https://github.com/phuchoang2603/k8s-deploy.git"
    # valuesTargetRevision: "master"
    # valuesFile: argo-apps/loki.yaml
    valuesFile: deployments/argo-apps/values/loki.yaml

  k8s-monitoring:
    enabled: true
    destinationNamespace: monitoring
    path: deployments/helm-charts/k8s-monitoring
    valuesFile: deployments/argo-apps/values/k8s-monitoring.yaml

  kube-prometheus-stack:
    enabled: true
    destinationNamespace: monitoring
    path: deployments/helm-charts/kube-prometheus-stack
    valuesFile: deployments/argo-apps/values/kube-prometheus-stack.yaml

  tempo:
    enabled: true
    destinationNamespace: monitoring
    path: deployments/helm-charts/tempo
    valuesFile: deployments/argo-apps/values/tempo.yaml

  fraud-detection:
    enabled: true
    destinationNamespace: model-serving
    path: deployments/helm-charts/fraud-detection
    valuesFile: deployments/argo-apps/values/fraud-detection.yaml

  traefik:
    enabled: true
    destinationNamespace: api-gateway
    path: deployments/helm-charts/traefik
    valuesFile: deployments/argo-apps/values/traefik.yaml

  cert-manager:
    enabled: true
    destinationNamespace: api-gateway
    path: deployments/helm-charts/cert-manager
    valuesFile: deployments/argo-apps/values/cert-manager.yaml

  # Regular manifest files of ingressroute, cert-manager issuers, ...
cloud:
  enabled: true
  # repoURL: "https://github.com/phuchoang2603/k8s-deploy.git"
  # targetRevision: "master"
  # path: argo-apps/cloud
  path: deployments/argo-apps/values/cloud
  destinationNamespace: default
