[project]
name = "realtime-credit-card-fraud-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.uv.workspace]
members = [
    "notebooks/project",
    "notebooks",
]
