apiVersion: v2
appVersion: 3.0.2
dependencies:
- alias: annotationAutodiscovery
  condition: annotationAutodiscovery.enabled
  name: feature-annotation-autodiscovery
  repository: ""
  version: 1.0.0
- alias: applicationObservability
  condition: applicationObservability.enabled
  name: feature-application-observability
  repository: ""
  version: 1.0.0
- alias: autoInstrumentation
  condition: autoInstrumentation.enabled
  name: feature-auto-instrumentation
  repository: ""
  version: 1.0.0
- alias: clusterEvents
  condition: clusterEvents.enabled
  name: feature-cluster-events
  repository: ""
  version: 1.0.0
- alias: clusterMetrics
  condition: clusterMetrics.enabled
  name: feature-cluster-metrics
  repository: ""
  version: 1.0.0
- alias: integrations
  name: feature-integrations
  repository: ""
  version: 1.0.0
- alias: nodeLogs
  condition: nodeLogs.enabled
  name: feature-node-logs
  repository: ""
  version: 1.0.0
- alias: podLogs
  condition: podLogs.enabled
  name: feature-pod-logs
  repository: ""
  version: 1.0.0
- alias: profiling
  condition: profiling.enabled
  name: feature-profiling
  repository: ""
  version: 1.0.0
- alias: prometheusOperatorObjects
  condition: prometheusOperatorObjects.enabled
  name: feature-prometheus-operator-objects
  repository: ""
  version: 1.0.0
- condition: alloy-operator.deploy
  name: alloy-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.3.2
description: Capture all telemetry data from your Kubernetes cluster.
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
maintainers:
- email: pete.wall@grafana.com
  name: petewall
- email: robert.lankford@grafana.com
  name: rlankfo
name: k8s-monitoring
sources:
- https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring
type: application
version: 3.0.2
