apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-monitoring
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.global.destinationServer | quote }}
    namespace: {{ .Values.applications.k8sMonitoring.destinationNamespace | quote }}
  sources:
    - repoURL: {{ default .Values.global.repoURL .Values.applications.k8sMonitoring.repoURL | quote }}
      path: {{ .Values.applications.k8sMonitoring.path | quote }}
      targetRevision: {{ default .Values.global.targetRevision .Values.applications.k8sMonitoring.targetRevision | quote }}
      helm:
        valueFiles:
          - $values/{{ .Values.applications.k8sMonitoring.valuesFile }}
    - repoURL: {{ default .Values.global.repoURL .Values.applications.k8sMonitoring.repoURL | quote }}
      targetRevision: {{ default .Values.global.targetRevision .Values.applications.k8sMonitoring.targetRevision | quote }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
