---
# -- Overrides the chart's name. Used to change the infix in the resource names.
nameOverride: null
# -- Overrides the chart's computed fullname. Used to change the full prefix of
# resource names.
fullnameOverride: null

global:
  image:
    # -- Global image registry override.
    # @section -- Image Settings
    registry: ""

    # -- Global image pull secrets.
    # @section -- Image Settings
    pullSecrets: []

# -- How many replicas to use for the Alloy Operator Deployment.
# @section -- Deployment Settings
replicaCount: 1

image:
  # -- Alloy Operator image registry
  # @section -- Image Settings
  registry: ghcr.io

  # -- Alloy Operator image repository
  # @section -- Image Settings
  repository: grafana/alloy-operator

  # -- Alloy Operator image tag. When empty, the Chart's appVersion is used.
  # @section -- Image Settings
  tag: ""

  # -- The pull policy for images.
  # @section -- Image Settings
  pullPolicy: IfNotPresent

  # -- Optional set of image pull secrets.
  # @section -- Image Settings
  pullSecrets: []

# Service Account settings
serviceAccount:
  # -- Whether to create a service account for the Alloy Operator deployment.
  # @section -- Service Account Settings
  create: true
  # -- Whether the Alloy Operator pod should automatically mount the service account token.
  # @section -- Service Account Settings
  automount: true
  # -- Annotations to add to the service account
  # @section -- Service Account Settings
  annotations: {}
  # -- Additional labels to add to the service account
  # @section -- Service Account Settings
  labels: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # @section -- Service Account Settings
  name: ""

# -- Additional annotations to add to the pod.
# @section -- Pod Settings
podAnnotations: {}

# -- Additional labels to add to the pod.
# @section -- Pod Settings
podLabels: {}

# -- Set the security context for the pod.
# Example: podSecurityContext: { fsGroup: 2000 }
# @section -- Pod Settings
podSecurityContext: {}

# -- Set the security context for the operator container.
# @section -- Container Settings
securityContext:
  runAsNonRoot: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsUser: 1000

service:
  # -- The type of service to create for the operator.
  # @section -- Service
  type: ClusterIP

  health:
    # -- The port number for the health probes.
    # @section -- Service
    port: 8081

  metrics:
    # -- The port number for the metrics service.
    # @section -- Service
    port: 8082

# Sets the resources for the pod.
resources:
  # -- Set the resource requests for the pod.
  # @section -- Resources
  requests:
    cpu: 10m
    memory: 64Mi

  # -- Set the resource limits for the pod.
  # @section -- Resources
  limits:
    cpu: 500m
    memory: 128Mi

# -- Liveness probe settings
# @section -- Probes
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

# -- Readiness probe settings
# @section -- Probes
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

# -- Set the node selector for the pod.
# @section -- Pod Settings
nodeSelector:
  kubernetes.io/os: linux

# -- Set the tolerations for the pod.
# @section -- Pod Settings
tolerations: []

# -- Set the affinity for the pod.
# @section -- Pod Settings
affinity: {}

# Handling of the CustomResourceDefinitions (CRDs)
crds:
  # -- Should this chart deploy the Alloy CRD?
  # @section -- CRDs
  deployAlloyCRD: true

  # -- Should this chart deploy the PodLogs CRD?
  # @section -- CRDs
  deployPodLogsCRD: false
