{{- if .Values.applications.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
spec:
  project: default
  destination:
    server: {{ .Values.global.destinationServer | quote }}
    namespace: {{ .Values.applications.traefik.destinationNamespace | quote }}
  sources:
    # Source 1: The official Traefik Helm chart
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: {{ .Values.applications.traefik.chartVersion | quote }}
      helm:
        valueFiles:
          - $values/{{ .Values.applications.traefik.valuesFile }}
          
    - repoURL: {{ .Values.global.repoURL | quote }}
      targetRevision: {{ .Values.global.targetRevision | quote }}
      ref: values
      
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
{{- end }}
