{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ $.Release.Name }}-{{ $.Chart.Name }}
          port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
