apiVersion: v1
kind: Service
metadata:
  name: {{ include "{{ .Chart.Name }}.fullname" . }}
  labels:
    {{- include "{{ .Chart.Name }}.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 8010
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 4 }}
