alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  defaultFlagsOverride:
    - --enable-feature=exemplar-storage
    - --enable-feature=native-histograms
  extraArgs:
    web.enable-remote-write-receiver: true
