# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fraud.v1 import fraud_pb2 as fraud_dot_v1_dot_fraud__pb2


class FraudServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/fraud.v1.FraudService/Predict',
                request_serializer=fraud_dot_v1_dot_fraud__pb2.PredictRequest.SerializeToString,
                response_deserializer=fraud_dot_v1_dot_fraud__pb2.PredictResponse.FromString,
                _registered_method=True)


class FraudServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=fraud_dot_v1_dot_fraud__pb2.PredictRequest.FromString,
                    response_serializer=fraud_dot_v1_dot_fraud__pb2.PredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud.v1.FraudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud.v1.FraudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud.v1.FraudService/Predict',
            fraud_dot_v1_dot_fraud__pb2.PredictRequest.SerializeToString,
            fraud_dot_v1_dot_fraud__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
