apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.global.destinationServer | quote }}
    namespace: {{ .Values.applications.grafana.destinationNamespace | quote }}
  sources:
    - repoURL: {{ default .Values.global.repoURL .Values.applications.grafana.repoURL | quote }}
      path: {{ .Values.applications.grafana.path | quote }}
      targetRevision: {{ default .Values.global.targetRevision .Values.applications.grafana.targetRevision | quote }}
      helm:
        valueFiles:
          - $values/{{ .Values.applications.grafana.valuesFile }}
    - repoURL: {{ default .Values.global.repoURL .Values.applications.grafana.repoURL | quote }}
      targetRevision: {{ default .Values.global.targetRevision .Values.applications.grafana.targetRevision | quote }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
# The standalone IngressRoute is kept as a static part of this template
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: {{ .Values.applications.grafana.destinationNamespace | quote }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.home.phuchoang.sbs`)
      kind: Rule
      services:
        - name: grafana
          port: 80
