apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-detection
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: {{ .Values.global.destinationServer | quote }}
    namespace: {{ .Values.applications.modelServing.destinationNamespace | quote }}
  sources:
    - repoURL: {{ default .Values.global.repoURL .Values.applications.modelServing.repoURL | quote }}
      path: {{ .Values.applications.modelServing.path | quote }}
      targetRevision: {{ default .Values.global.targetRevision .Values.applications.modelServing.targetRevision | quote }}
      helm:
        valueFiles:
          - $values/{{ .Values.applications.modelServing.valuesFile }}
    - repoURL: {{ default .Values.global.repoURL .Values.applications.modelServing.repoURL | quote }}
      targetRevision: {{ default .Values.global.targetRevision .Values.applications.modelServing.targetRevision | quote }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: model-serving-ingress
  namespace: {{ .Values.applications.modelServing.destinationNamespace | quote }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fraud.home.phuchoang.sbs`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: fraud-detection
          port: 8000
