global:
  repoURL: https://github.com/phuchoang2603/realtime-credit-card-fraud-detection.git
  targetRevision: main
destinationName: dev
namePrefix: payment-gateway-dev
applications:
  fraud-service:
    enabled: true
    destinationNamespace: payment-gateway
    path: infra/charts/fraud-service
    valuesFile: []
