apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-gateway-prod-root
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: realtime-credit-card-fraud-detection
  source:
    repoURL: https://github.com/phuchoang2603/realtime-credit-card-fraud-detection.git
    targetRevision: &revision main
    path: infra/argocd/app-of-apps
    helm:
      releaseName: payment-gateway-prod
      valuesObject:
        global:
          targetRevision: *revision
        namePrefix: payment-gateway-prod
        destinationServer: https://kubernetes.default.svc
        applications:
          fraud-service:
            enabled: false
            valuesFile:
              - infra/charts/fraud-service/values-prod.yaml
          secret-store:
            enabled: true
            destinationNamespace: argo-cd
            path: infra/charts/secret-store
            valuesFile:
              - infra/charts/secret-store/values-prod.yaml
            syncRetry:
              limit: -1
              backoff:
                duration: 5s
                factor: 2
                maxDuration: 3m
          kubeflow-workspace:
            enabled: true
            destinationNamespace: argo-cd
            path: infra/charts/kubeflow-workspace
            syncRetry:
              limit: -1
              backoff:
                duration: 5s
                factor: 2
                maxDuration: 3m
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
