ingress:
  enabled: false

image:
  pullPolicy: Always
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  - name: MODEL_PATH
    value: /app/models/model.pkl

telemetry:
  serviceName: fraud-service
  traceEndpoint: vtsingle-vmks.monitoring.svc.cluster.local:4317
