ingress:
  enabled: true
  name: payment-gateway-ingress
  hostname: fraud.phuchoang.sbs
  port: 80

image:
  tag: "v1.1.0"
  pullPolicy: Always
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  - name: MODEL_PATH
    value: /app/models/model.pkl

telemetry:
  serviceName: fraud-service
  traceEndpoint: vtsingle-vmks.monitoring.svc.cluster.local:4317
