apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: api-gateway
type: Opaque
stringData:
  api-token: "lyjbLan5ApshVxTktZRxgXZm3DkzQeT8vUxK_1sW"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    email: xuanphuc.a1gv@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
