apiVersion: v2
appVersion: 1.0.0
dependencies:
- condition: kube-state-metrics.deploy
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.33.1
- alias: node-exporter
  condition: node-exporter.deploy
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.46.0
- alias: windows-exporter
  condition: windows-exporter.deploy
  name: prometheus-windows-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 0.10.1
- condition: kepler.enabled
  name: kepler
  repository: https://sustainable-computing-io.github.io/kepler-helm-chart
  version: 0.6.0
- condition: opencost.enabled
  name: opencost
  repository: https://opencost.github.io/opencost-helm-chart
  version: 1.43.2
description: Gathers Kubernetes Cluster metrics
icon: https://raw.githubusercontent.com/grafana/grafana/main/public/img/grafana_icon.svg
maintainers:
- email: pete.wall@grafana.com
  name: petewall
name: feature-cluster-metrics
sources:
- https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/charts/feature-cluster-metrics
version: 1.0.0
