service:
  type: LoadBalancer
  # Set default IP for proxmox rke2 cluster
  # spec:
  #   loadBalancerIP: "10.69.3.3"

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-tls

ingressRoute:
  dashboard:
    enabled: true
    # matchRule: Host(`traefik.home.phuchoang.sbs`)
    matchRule: Host(`traefik.cloud.phuchoang.sbs`)
    entryPoints: ["websecure"]

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
