service:
  type: LoadBalancer
  # spec:
  #   loadBalancerIP: "10.69.3.3"

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-tls

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
