{
 "title": "House Price Prediction API",
 "templating": {
  "list": [
   { "name": "query", "label": "Log Filter" }
  ]
 },
 "panels": [
  {
   "title": "Prediction Duration (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "milliseconds" } },
   "targets": [
    {
     "expr": "rate(predict_duration_seconds_sum[1m]) / rate(predict_duration_seconds_count[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Predictions",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(app_requests_total{endpoint=\"/predict\", http_status=\"200\"})"
    }
   ]
  },
  {
   "title": "Validation Errors (422)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(app_requests_total{endpoint=\"/predict\", http_status=\"422\"})"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(app_requests_total{http_status!=\"200\"}) / sum(app_requests_total)"
    }
   ]
  },
  {
   "title": "FastAPI Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{container=\"house-price-prediction\"} |= \"$query\""
    }
   ]
  }
 ]
}