apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlpipeline-minio-artifact
  namespace: fraud-ml-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: mlpipeline-minio-artifact
  data:
    - secretKey: accesskey
      remoteRef:
        key: KUBEFLOW_RUSTFS_ACCESS_KEY
    - secretKey: secretkey
      remoteRef:
        key: KUBEFLOW_RUSTFS_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: model-registry-db-secrets
  namespace: fraud-ml-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: model-registry-db-secrets
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: {{ `"{{ .password }}"` }}
  data:
    - secretKey: password
      remoteRef:
        key: KUBEFLOW_REGISTRY_DB_PASSWORD
