apiVersion: v1
kind: ConfigMap
metadata:
  name: kfp-launcher
  namespace: fraud-ml-prod
data:
  defaultPipelineRoot: s3://kubeflow-prod-pipelines/artifacts
  providers: |
    s3:
      default:
        endpoint: https://minio.home.phuchoang.sbs
        disableSSL: false
        region: us-east-1
        forcePathStyle: true
        credentials:
          fromEnv: false
          secretRef:
            secretName: mlpipeline-minio-artifact
            accessKeyKey: accesskey
            secretKeyKey: secretkey
