name: Linting and Test

on:
  pull_request:
    paths:
      - "app/**"

jobs:
  lint:
    name: Lint with Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install Lint Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.1.1 flake8_black==0.3.6

      - name: Run flake8
        run: |
          flake8 --max-line-length=119 \
                 --ignore=E722,I201,I100,BLK100,W503 \
                 --per-file-ignores=__init__.py:F401 \
                 app/*.py

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
      PYTHONPATH: ${{ github.workspace }}
      TESTING_MODE: "true"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run Pytest
        run: |
          uv run pytest --cov=app --cov-report=term-missing --cov-fail-under=80 tests/
