apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      # This links Loki traces to the Prometheus data source
      derivedFields:
        - datasourceUid: "Prometheus" # Use the UID of the Prometheus data source
          matcherRegex: 'traceID=(\w+)'
          name: "TraceID"
          url: "$${__value.raw}"
