{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ required "secretStore.name is required" .Values.secretStore.name }}
  namespace: {{ required "secretStore.namespace is required" .Values.secretStore.namespace }}
spec:
  provider:
    doppler:
      project: {{ required "secretStore.project is required" .Values.secretStore.project }}
      config: {{ required "secretStore.config is required" .Values.secretStore.config }}
      auth:
        secretRef:
          dopplerToken:
            name: {{ required "secretStore.tokenSecret.name is required" .Values.secretStore.tokenSecret.name }}
            key: {{ required "secretStore.tokenSecret.key is required" .Values.secretStore.tokenSecret.key }}
{{- end }}
